apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "tuesday"
  description: "demo for architecture"
  annotations:
    github.com/project-slug: lab49-poc/tuesday
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - springboot
    - kubernetes
    - aws-eks
    - rest
  links:
    - title: health status
      ### DATA_PLANE_LB needs to be configured and plugged in
      url: https://a20df726a16ea4cbdb91c30c2f82a6b2-1628815465.ap-southeast-2.elb.amazonaws.com/tuesday/actuator/health
      icon: dashboard
      ### domain name needs to be configured
    - title: kong manager
      url: http://a3f9fd27125c640cc8ce3f1d4f2ae5b0-1987737800.ap-southeast-2.elb.amazonaws.com:8002/overview
      icon: dashboard
spec:
  type: service
  lifecycle: experimental
  owner: "teama"
  providesApis:
    - tuesday
#  consumesApis:
#    - petstore
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: tuesday
  description: demo for architecture
spec:
  type: openapi
  lifecycle: experimental
  owner: lab49-poc
  definition:
    $text: https://github.com/lab49-poc/tuesday/blob/master/src/main/resources/api-docs.yaml
